export const MUSIC_GENRE = [
	'Alternative rock',
	'Ambient music',
	'Conscious hip hop',
	'Contemporary Christian music',
	'Country music',
	'Dance-pop',
	'Drill music',
	'Electro house',
	'Electronic dance music',
	'Electronic music',
	'Electronica',
	'Electronicore',
	'Emo',
	'Emo rap',
	'Enka',
	'Fado',
	'Freakbeat',
	'Funk',
	'Hip hop music',
	'House music',
	'Hyperpop',
	'Indie pop',
	'Indie rock',
	'Jazz',
	'Lo-Fi',
	'Melodic metalcore',
	'Nerdcore',
	'Neurofunk',
	'Nintendocore',
	'Pop music',
	'Pop rock',
	'Pop-punk',
	'Post-punk',
	'Psychedelic rock',
	'Punk rock',
	'Qawwali',
	'Rap metal',
	'Rhythm and blues',
	'Rock',
	'Screamo',
	'Sega',
	'Shoegaze',
	'Skweee',
	'Soca music',
	'Soukous',
	'Straight edge',
	'Synth-pop',
	'Teen pop',
	'Wave',
	'Zouk',
	'Zydeco'
];
